import { z } from 'zod';

const configSchema = z.object({
  databaseUrl: z.string().min(1),
  brainAccessKey: z.string().min(1),
  slackBotToken: z.string().min(1).optional(),
  slackSigningSecret: z.string().min(1).optional(),
  telegramBotToken: z.string().min(1).optional(),
  telegramWebhookSecret: z.string().min(1).optional(),
  serpApiKey: z.string().min(1).optional(),
  fathomApiKey: z.string().min(1).optional(),
  fathomWebhookSecret: z.string().min(1).optional(),
  ollamaBaseUrl: z.string().default('http://localhost:11434'),
  embeddingModel: z.string().default('nomic-embed-text'),
  extractionModel: z.string().default('llama3.3:70b'),
  chatModel: z.string().default('llama3.3:70b'),
  relationshipModel: z.string().min(1).optional(),
  mcpPort: z.number().int().default(3000),
  pollIntervalMs: z.number().int().default(5000),
  batchSize: z.number().int().default(5),
  maxRetries: z.number().int().default(3),
  rawFilesDir: z.string().default('./data/raw-files'),
  whisperBaseUrl: z.string().default('http://localhost:8001'),
  whisperModel: z.string().default('large-v3'),
  transcribeDir: z.string().default('./data/transcriptions'),
  jwtSecret: z.string().min(32).optional(),
  hubspotAccessToken: z.string().min(1).optional(),
  hubspotWebhookSecret: z.string().min(1).optional(),
  hubspotPollIntervalMs: z.number().int().default(300_000),
  hubspotObjectTypes: z.string().default('contacts,companies,deals,notes,calls,emails,meetings,tasks'),
  hubspotRequireContactActivity: z.boolean().default(true),
  rerankerModel: z.string().min(1).optional(),
});

export type Config = z.infer<typeof configSchema>;

export function loadConfig(): Config {
  return configSchema.parse({
    databaseUrl: process.env.DATABASE_URL,
    brainAccessKey: process.env.BRAIN_ACCESS_KEY,
    slackBotToken: process.env.SLACK_BOT_TOKEN || undefined,
    slackSigningSecret: process.env.SLACK_SIGNING_SECRET || undefined,
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN || undefined,
    telegramWebhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET || undefined,
    serpApiKey: process.env.SERPAPI_KEY || undefined,
    fathomApiKey: process.env.FATHOM_API_KEY || undefined,
    fathomWebhookSecret: process.env.FATHOM_WEBHOOK_SECRET || undefined,
    ollamaBaseUrl: process.env.OLLAMA_BASE_URL || undefined,
    embeddingModel: process.env.EMBEDDING_MODEL || undefined,
    extractionModel: process.env.EXTRACTION_MODEL || undefined,
    chatModel: process.env.CHAT_MODEL || undefined,
    relationshipModel: process.env.RELATIONSHIP_MODEL || undefined,
    mcpPort: process.env.MCP_PORT ? parseInt(process.env.MCP_PORT, 10) : undefined,
    pollIntervalMs: process.env.POLL_INTERVAL_MS ? parseInt(process.env.POLL_INTERVAL_MS, 10) : undefined,
    batchSize: process.env.BATCH_SIZE ? parseInt(process.env.BATCH_SIZE, 10) : undefined,
    maxRetries: process.env.MAX_RETRIES ? parseInt(process.env.MAX_RETRIES, 10) : undefined,
    rawFilesDir: process.env.RAW_FILES_DIR || undefined,
    whisperBaseUrl: process.env.WHISPER_BASE_URL || undefined,
    whisperModel: process.env.WHISPER_MODEL || undefined,
    transcribeDir: process.env.TRANSCRIBE_DIR || undefined,
    jwtSecret: process.env.JWT_SECRET || undefined,
    hubspotAccessToken: process.env.HUBSPOT_ACCESS_TOKEN || undefined,
    hubspotWebhookSecret: process.env.HUBSPOT_WEBHOOK_SECRET || undefined,
    hubspotPollIntervalMs: process.env.HUBSPOT_POLL_INTERVAL_MS ? parseInt(process.env.HUBSPOT_POLL_INTERVAL_MS, 10) : undefined,
    hubspotObjectTypes: process.env.HUBSPOT_OBJECT_TYPES || undefined,
    hubspotRequireContactActivity: process.env.HUBSPOT_REQUIRE_CONTACT_ACTIVITY === 'false' ? false : undefined,
    rerankerModel: process.env.RERANKER_MODEL || undefined,
  });
}
